import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { formatPrice, gql, storefront } from "pages/api/storefront";
import { useEffect, useState } from "react";

export async function getStaticPaths() {
  const { data } = await storefront(
    gql`
      {
        products(first: 8) {
          edges {
            node {
              handle
            }
          }
        }
      }
    `
  );
  return {
    paths: data.products.edges.map(({ node }) => ({
      params: {
        handle: node.handle,
      },
    })),
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const { data } = await storefront(singleProductQuery(params.handle));
  return {
    props: {
      singleProduct: data.productByHandle,
      products: data.products,
    },
  };
}

const singleProductQuery = (handle) => gql`
{
productByHandle(handle: "${handle}") {
    title
    handle
    description
    priceRange {
      minVariantPrice {
        amount
      }
    }
    images(first: 1) {
    edges {
        node {
        url
        altText
        }
    }
    }
}
products(first: 8) {
  edges {
    node {
      title
      handle
      productType
      priceRange {
        minVariantPrice {
          amount
        }
      }
      images(first: 1) {
        edges {
          node {
            url
            altText
          }
        }
      }
    }
  }
}
}
`;

function Products({ singleProduct, products }) {
  const image = singleProduct.images.edges[0].node;
  const product = singleProduct;
  const price = singleProduct.priceRange;
  const [slicedProducts, setSlicedProducts] = useState([]);

  useEffect(() => {
    const relatedProducts = products.edges.filter(
      ({ node: { handle } }) => handle !== singleProduct.handle
    );

    for (let i = relatedProducts.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [relatedProducts[i], relatedProducts[j]] = [
        relatedProducts[j],
        relatedProducts[i],
      ];
    }

    const slicedProducts = relatedProducts.slice(0, 4);
    setSlicedProducts(slicedProducts);
  }, [products, singleProduct.handle]);

  return (
    <>
      <Head>
        <title>{product.title} | Oukthy Shop </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content="Home" />
        <meta
          property="og:description"
          content="Generated by create next app"
        />
        <meta property="og:image" content="/favicon.ico" />
        <meta property="og:url" content="https://www.example.com" />
      </Head>

      <section>
        <div className="products__inner">
          <h1>{product.title}</h1>
          <Image
            width={286}
            height={429}
            src={image.url}
            alt={image.altText}
            className="products__inner__image"
            priority
            style={{
              height: "auto",
              width: "auto",
            }}
          />
          <p>{formatPrice(price.minVariantPrice.amount)}</p>
        </div>
        <div className="products__related">
          <h2>Related Products</h2>
          <div className="products__related__inner">
            {slicedProducts.map(({ node }) => (
              <div key={node.handle} className="products__related__inner__item">
                <Link href={`/products/${node.handle}`}>
                  <Image
                    width={286}
                    height={429}
                    src={node.images.edges[0].node.url}
                    alt={node.images.edges[0].node.altText}
                    priority
                    style={{
                      height: "auto",
                      width: "auto",
                    }}
                  />
                </Link>
                <h3>{node.title}</h3>
                <p>{formatPrice(node.priceRange.minVariantPrice.amount)}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}

export default Products;
